# Generated by Django 4.1.5 on 2023-01-04 13:55

from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# polls.migrations.0003_auto_20230104_2151

class Migration(migrations.Migration):
    replaces = [('polls', '0001_initial'), ('polls', '0002_poll_pub_date'), ('polls', '0003_auto_20230104_2151')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                # ('pub_date', models.DateTimeField(default=datetime.datetime(2023, 1, 4, 13, 47, 30, 411648, tzinfo=datetime.timezone.utc), verbose_name='date published')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        # migrations.RunPython(
        #     code=polls.migrations.0003_auto_20230104_2151.forward_pub_date_by_one_day,
        #     reverse_code=polls.migrations.0003_auto_20230104_2151.backward_pub_date_by_one_day,
        # ),
    ]
