# Generated by Django 4.1.5 on 2023-01-04 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="pub_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 1, 4, 13, 47, 30, 411648, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date published",
            ),
            preserve_default=False,
        ),
    ]
