openapi: "3.0.0"
info:
  title: Banking API
  version: "1.0"
  description: A simple banking API
paths:
  /beneficiaries:
    post:
      description: Adds a money transfer beneficiary
      responses:
        "201":
          description: Beneficiary added
    get:
      description: Gets beneficiaries list
      responses:
        "200":
          description: The beneficiaries list
  /accounts/{id}:
    get:
      summary: Gets an account
      parameters:
        - name: id
          in: path
          description: Account's id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: The account
  /transfers:
    get:
      summary: Gets transfers list
      responses:
        "200":
          description: The transfers list
    post:
      summary: Transfers money
      responses:
        "201":
          description: Immediate transfer request done
        "202":
          description: Delayed transfer pending
  /beneficiaries/{id}:
    parameters:
      - name: id
        in: path
        description: Beneficiary's id
        required: true
        schema:
          type: string
    delete:
      description: Deletes a beneficiary
      responses:
        "204":
          description: Beneficiary deleted
    get:
      description: Gets a beneficiary
      responses:
        "200":
          description: The beneficiary
  /accounts:
    get:
      summary: Gets accounts list
      responses:
        "200":
          description: User's accounts
  /transfers/{id}:
    parameters:
      - name: id
        in: path
        description: Transfer's id
        required: true
        schema:
          type: string
    get:
      description: Gets a transfer
      responses:
        "200":
          description: The transfer
    delete:
      description: Deletes a transfer
      responses:
        "204":
          description: Transfer deleted
