openapi: "3.0.0"
info:
  title: Shopping API
  version: "1.0"
paths:
  /products:
    description: The products catalog
    get:
      summary: Search for products
      parameters: 
        - name: free-query
          description: free query
          in: query
          schema:
            type: string
      responses:
        "200":
          description: products matching free query
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    name:
                      type: string
                    price:
                      type: number